services:
  postgres:
    image: postgres:16
    container_name: postgres-db
    restart: always

    environment:
      POSTGRES_DB: ${DB_DATABASE:-comida_db}
      POSTGRES_USER: ${DB_USER:-admin}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-Atilas123*}
    expose:
      - 5432
    #ports:
    #  - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

    networks:
      - oracle-apex-networks

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always

    environment:
      PGADMIN_DEFAULT_EMAIL: eddy9062@test.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    expose:
      - 80
    #ports:
    #  - "8080:80"

    networks:
      - oracle-apex-networks
    labels:
      - "traefik.enable=true"
      - "traefik.http.middlewares.comedor-pgadmin-prefix.stripprefix.prefixes=/pga"
      - "traefik.http.routers.comedor-pgadmin.middlewares=comedor-pgadmin-prefix"
      - "traefik.http.routers.comedor-pgadmin.rule=Host(`sistema-pv.ddns.net`) && PathPrefix(`/pga`)"
      - "traefik.http.routers.comedor-pgadmin.entrypoints=websecure"
      - "traefik.http.routers.comedor-pgadmin.tls=true"
      - "traefik.http.routers.comedor-pgadmin.tls.certresolver=lets-encrypt"
      - "traefik.http.services.comedor-pgadmin.loadbalancer.server.port=80" 

  comida-server:
    container_name: comida-server
    volumes:
      - /root/docker/volumes/imgcome:/usr/src/app/uploads
    environment:
      - NODE_ENV=production
      - PORT=3000
      - DB_USER=${DB_USER:-admin}
      - DB_PASSWORD=${DB_PASSWORD:-Atilas123*}
      - DB_DATABASE=${DB_DATABASE:-comida_db}
      - DB_HOST=${DB_HOST:-postgres}
      - DB_PORT=${DB_PORT:-5432}
      - DB_SSL=${DB_SSL:-false}
      - JWT_SECRET=${JWT_SECRET:-secretkeyjireh}
      - JWT_EXPIRES_IN=${JWT_EXPIRES_IN:-15d}
      - CORS_ORIGIN=${CORS_ORIGIN:-*}
      - JSON_LIMIT=${JSON_LIMIT:-50mb}
    build:
      context: ./ComidaServer
      dockerfile: Dockerfile
    image: comida-server:0.0.1
    expose:
      - 3000
    #ports:
    # - 3000:3000
    restart: always
    depends_on:
      - postgres
    networks:
      - oracle-apex-networks
    labels:
      - "traefik.enable=true"
      - "traefik.http.middlewares.comedor-api-prefix.stripprefix.prefixes=/comeserver"
      - "traefik.http.routers.comedor-api.middlewares=comedor-api-prefix"
      - "traefik.http.routers.comedor-api.rule=Host(`sistema-pv.ddns.net`) && PathPrefix(`/comeserver`)"
      - "traefik.http.routers.comedor-api.entrypoints=websecure"
      - "traefik.http.routers.comedor-api.tls=true"
      - "traefik.http.routers.comedor-api.tls.certresolver=lets-encrypt"
      - "traefik.http.services.comedor-api.loadbalancer.server.port=3000"

volumes:
  postgres_data:

networks:
  oracle-apex-networks:
    external: true